config-version: 1

settings:
  default-language: en
  block-all-item-drops: false
  block-managed-item-drops: true
  lock-managed-items-in-inventory: true
  clear-cooldowns-on-quit: false
  forced-join-held-slot: 0

lobby:
  world: ''
  x: 0.5
  y: 64.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0
